### ISSUE TITLE
serial_driver dependency does not add to CMakeLists.txt

### ISSUE THREAD

**Issue by Ericsii** [chenjunnn/rm_pioneer_vision#5]
https://github.com/chenjunnn/rm_vision/blob/45331bf3dcb3256b2e22095e9d65735ec617fbdb/rm_serial_driver/CMakeLists.txt

**Comment by chenjunnn** [comment]
I used ament_cmake_auto macro to find dependencies automatically
https://github.com/chenjunnn/rm_vision/blob/45331bf3dcb3256b2e22095e9d65735ec617fbdb/rm_serial_driver/CMakeLists.txt#L20
